Reimplement `probe` / `probe_all` with revertible database
exonum/exonum-testkit pull request #8
Opened 2017-12-08 14:17 UTC by slowli

This PR introduces `CheckpointDb` - a `Database` implementation that allows to revert merges. `probe()` and `probe_all()` methods are re-implemented accordingly.

Supersedes #1.

2017-12-11 09:17 UTC, stanislav-tkach submitted a review, later dismissed

2017-12-16 13:56 UTC, stanislav-tkach submitted a review, later dismissed

2017-12-19 07:47 UTC, stanislav-tkach submitted a review, later dismissed

2017-12-19 08:00 UTC, aleksuss submitted a review, later dismissed

2017-12-19 08:16 UTC, alekseysidorov requested changes

2017-12-19 08:16 UTC, alekseysidorov commented on src/lib.rs
> +    /// ```ignore
May you make this test compileable?

2017-12-19 11:20 UTC, alekseysidorov commented
"This branch is out-of-date with the base branch"

2017-12-19 11:24 UTC, slowli commented
@alekseysidorov And I also have forgotten to update the changelog. Woe is me 😣

2017-12-19 12:09 UTC, stanislav-tkach approved these changes

2017-12-19 13:12 UTC, alekseysidorov approved these changes

2017-12-19 13:12 UTC, merged